# Bash default commands replacement
brew "zoxide"
brew "eza"
brew "ripgrep"
brew "bat"
brew "fd"

# Terminal ultilities
brew "neovim"
brew "tmux"
brew "fzf"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "btop"
brew "tlrc"
brew "stow"
brew "mole"
brew "starship"
brew "fastfetch"

# Developer tools
brew "git"
brew "uv"
brew "bun"
brew "node"
brew "docker"
brew "docker-compose"
brew "colima"
brew "kubernetes-cli"
brew "lazydocker"
brew "lazygit"

# zsh
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

