[dotfiles]
"~/.config/aerospace" = "~/.dotfiles/aerospace/.config/aerospace"
"~/.config/borders" = "~/.dotfiles/borders/.config/borders"
"~/.config/sketchybar" = "~/.dotfiles/sketchybar/.config/sketchybar"

[bootstrap.macos.dock]
autohide = true
# autohide-time-modifier = 0
# autohide-delay = 0

[bootstrap.hooks]
post-defaults = "killall Dock"

