set -g mouse on
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g focus-events on

# Remaps
unbind C-b
set -g prefix C-Space
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Open new panes/windows in the same directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Palette
rosewater="#f5e0dc"
flamingo="#f2cdcd"
pink="#f5c2e7"
mauve="#cba6f7"
red="#f38ba8"
maroon="#eba0ac"
peach="#fab387"
yellow="#f9e2af"
green="#a6e3a1"
teal="#94e2d5"
sky="#89dceb"
sapphire="#74c7ec"
blue="#89b4fa"
lavender="#b4befe"
text="#cdd6f4"
subtext1="#bac2de"
subtext0="#a6adc8"
overlay2="#9399b2"
overlay1="#7f849c"
overlay0="#6c7086"
surface2="#585b70"
surface1="#45475a"
surface0="#313244"
base="#1e1e2e"
mantle="#181825"
crust="#11111b"

# General
set-option -g status-position top
set -g status-left-length 100
set -g status-right-length 100
set -g base-index  1
set -g pane-base-index 1

# Status Bar theme
set -g status-style "fg=${text},bg=default"
set -g status-left " #[bold]#S"
set -g status-right "#[bold]#h "
set -g status-justify absolute-centre
set -g window-status-current-format "#[fg=${mauve},bold] #I:#W"
set -g window-status-format " #I:#W"
set -g message-style "fg=${crust},bg=${lavender}, fill=${lavender}"
set -g mode-style "fg=${crust},bg=${lavender}"
set -g pane-border-style "fg=${surface0}"
set -g pane-active-border-style "fg=${overlay0}"
set -g pane-border-lines heavy

# Plugins
set -g @plugin_path '~/.local/share/tmux/plugins/'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

