unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

set -g prefix C-Space

set -g mouse on
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g focus-events on

# Remaps
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Open new panes/windows in the same directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Color
text="#cdd6f4"
surface="#313244"
lavender="#b4befe"
mauve="#cba6f7"

# Status bar
set -g base-index  1
setw -g pane-base-index 1

set-option -g status-position top
set -g status-left-length 100
set -g status-right-length 100
set -g status-style "fg=${text},bg=default"
set -g status-left " #[fg=${text},bold]#S"
set -g status-right "#[fg=${text},bold]#h "
set -g status-justify absolute-centre
set -g window-status-current-format "#[fg=${mauve},bold] #I:#W"
set -g window-status-format " #I:#W"
set -g message-style "fg=${surface},bg=${lavender}"
set -g mode-style "fg=${surface},bg=${lavender}"

set -g pane-border-style "fg=${surface}"
set -g pane-active-border-style "fg=${lavender}"

# Plugins for sessions resurrect
set -g @plugin_path '~/.local/share/tmux/plugins/'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'
run '~/.tmux/plugins/tpm/tpm'

