#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="JetBrainsMono Nerd Font"
FONT_WEIGHT="Regular"
FONT_SIZE=14

HEIGHT=24
PADDINGS=3
BORDER_WIDTH=1
CORNER_RADIUS=20


sketchybar --bar height=$HEIGHT \
  color=$TRANSPARENT \
  padding_right=$PADDINGS \
  padding_left=$PADDINGS \
  y_offset=4 \
  margin=5 \
  \
  --default updates=when_shown \
  icon.font="$FONT:$FONT_WEIGHT:$FONT_SIZE" \
  icon.color=$ICON_ACCENT_COLOR \
  icon.padding_left=$PADDINGS \
  icon.padding_right=$PADDINGS \
  label.font="$FONT:$FONT_WEIGHT:$FONT_SIZE" \
  label.color=$LABEL_COLOR \
  label.padding_left=$PADDINGS \
  label.padding_right=$PADDINGS \
  background.padding_right=$PADDINGS \
  background.padding_left=$PADDINGS \

##### Spaces #####
sketchybar --add event aerospace_workspace_change
for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item "space.$sid" left \
    --subscribe "space.$sid" aerospace_workspace_change \
    --set "space.$sid" \
    icon.highlight_color=$ICON_ACCENT_COLOR \
    icon.padding_left=10 \
    click_script="aerospace workspace $sid" \
    script="$PLUGIN_DIR/spaces.sh $sid"
done

##### Calendar #####
sketchybar --add item calendar right \
  --subscribe calendar system_woke forced \
  --set calendar update_freq=10 \
  icon=󰃭 \
  script="$PLUGIN_DIR/calendar.sh"

##### Battery #####
sketchybar --add item battery right \
  --subscribe battery power_source_change system_woke front_app_switched \
  --set battery update_freq=15 \
  script="$PLUGIN_DIR/battery.sh"

##### Text Input #####
sketchybar --add event input_change \
  --add item text_input right \
  --subscribe text_input input_change \
  --set text_input update_freq=2 \
  icon=󰌌 \
  click_script="sketchybar --set \$NAME popup.drawing=toggle" \
  script="$PLUGIN_DIR/text_input.sh"

sketchybar --add bracket left_island '/space.*/' \
  --set left_island background.color=$BACKGROUND_COLOR \
  background.border_width=$BORDER_WIDTH \
  background.corner_radius=$CORNER_RADIUS \
  background.border_color=$BORDER_COLOR \
  background.height=$HEIGHT \
  background.drawing=on

sketchybar --add bracket right_island 'text_input' 'battery' 'calendar' \
  --set right_island background.color=$BACKGROUND_COLOR \
  background.border_width=$BORDER_WIDTH \
  background.corner_radius=$CORNER_RADIUS \
  background.border_color=$BORDER_COLOR \
  background.height=$HEIGHT \
  background.drawing=on

sketchybar --update

