#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
HELPER_DIR="$HOME/.config/sketchybar/helper"

FONT="JetBrainsMono Nerd Font"
FONT_WEIGHT="Regular"
FONT_SIZE=14

HEIGHT=24
PADDINGS=3
BORDER_WIDTH=1
CORNER_RADIUS=20
SHADOW=off

SPACE_CLICK_SCRIPT="aerospace workspace \$SID 2>/dev/null"

sketchybar --bar height=$HEIGHT \
  color=$TRANSPARENT \
  padding_right=$PADDINGS \
  padding_left=$PADDINGS \
  y_offset=4 \
  margin=5 \
  \
  --default updates=when_shown \
  icon.font="$FONT:$FONT_WEIGHT:$FONT_SIZE" \
  icon.color=$ICON_ACCENT_COLOR \
  icon.padding_left=$PADDINGS \
  icon.padding_right=$PADDINGS \
  label.font="$FONT:$FONT_WEIGHT:$FONT_SIZE" \
  label.color=$LABEL_COLOR \
  label.padding_left=$PADDINGS \
  label.padding_right=$PADDINGS \
  background.padding_right=$PADDINGS \
  background.padding_left=$PADDINGS \
  popup.background.border_width=$BORDER_WIDTH \
  popup.background.corner_radius=$CORNER_RADIUS \
  popup.background.border_color=$BORDER_COLOR \
  popup.background.color=$BACKGROUND_COLOR \
  popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/media.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/keyboard.sh"

sketchybar --add bracket left_island '/space.*/' \
  --set left_island background.color=$BACKGROUND_COLOR \
  background.border_width=$BORDER_WIDTH \
  background.corner_radius=$CORNER_RADIUS \
  background.border_color=$BORDER_COLOR \
  background.height=$HEIGHT \
  background.drawing=on

sketchybar --add bracket media_island 'media' \
  --set media_island background.color=$BACKGROUND_COLOR \
  background.border_width=$BORDER_WIDTH \
  background.corner_radius=$CORNER_RADIUS \
  background.border_color=$BORDER_COLOR \
  background.height=$HEIGHT \
  background.drawing=on

sketchybar --add bracket right_island 'keyboard' 'battery' 'calendar' \
  --set right_island background.color=$BACKGROUND_COLOR \
  background.border_width=$BORDER_WIDTH \
  background.corner_radius=$CORNER_RADIUS \
  background.border_color=$BORDER_COLOR \
  background.height=$HEIGHT \
  background.drawing=on

sketchybar --update

echo "sketchybar configuation loaded.."
