[settings]
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"

[tools]
antigravity-cli = "latest"
awscli = { version = "latest", symlink_bins = "true" }
bat = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
"github:alltuner/mise-completions-sync" = "latest"
go = "latest"
infisical = { version = "latest", asset_pattern = "cli_{{ version }}_{{ os(macos='darwin') }}_{{ arch(x64='amd64') }}.tar.gz" }
jq = "latest"
lazygit = "latest"
lazyssh = "latest"
neovim = "latest"
node = "latest"
"pipx:huggingface-hub" = "latest"
"pipx:kaggle" = "latest"
ripgrep = "latest"
sqlite = "latest"
starship = "latest"
tlrc = "latest"
tmux = "latest"
tree-sitter = "latest"
uv = "latest"
zoxide = "latest"

[dotfiles]
"~/.config/bat" = "~/.dotfiles/config/bat"
"~/.config/btop" = "~/.dotfiles/config/btop"
"~/.config/fastfetch" = "~/.dotfiles/config/fastfetch"
"~/.config/ghostty" = "~/.dotfiles/config/ghostty"
"~/.config/mise" = "~/.dotfiles/config/mise"
"~/.config/nvim" = "~/.dotfiles/config/nvim"
"~/.config/starship.toml" = "~/.dotfiles/config/starship/starship.toml"
"~/.config/tmux" = "~/.dotfiles/config/tmux"
"~/.config/zsh" = "~/.dotfiles/config/zsh"
"~/.zshenv" = "~/.dotfiles/zsh/.zshenv"

[bootstrap.hooks]
post-tools = """
TPM_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/tmux/plugins/tpm"

[ ! -d "$TPM_DIR" ] && git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"

"$TPM_DIR/bin/install_plugins"
"""
post-dotfiles = """
mise run bootstrap-personal
"""

[shell_alias]

