[settings]
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"
auto_update = true

[tools]
bat = "latest"
claude-code = "latest"
duckdb = "latest"
fd = "latest"
fzf = "latest"
"github:alltuner/mise-completions-sync" = "latest"
jq = "latest"
lazygit = "latest"
lazyssh = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "latest"
prettier = "latest"
ripgrep = "latest"
sqlite = "latest"
starship = "latest"
stylua = "latest"
tlrc = "latest"
tmux = "latest"
tree-sitter = "latest"
zoxide = "latest"

[dotfiles]
"~/.config/bat" = "~/.dotfiles/config/bat"
"~/.config/btop" = "~/.dotfiles/config/btop"
"~/.config/ghostty" = "~/.dotfiles/config/ghostty"
"~/.config/lazygit" = "~/.dotfiles/config/lazygit"
"~/.config/mise" = "~/.dotfiles/config/mise"
"~/.config/nvim" = "~/.dotfiles/config/nvim"
"~/.config/starship.toml" = "~/.dotfiles/config/starship/starship.toml"
"~/.config/tmux" = "~/.dotfiles/config/tmux"
"~/.config/vicinae" = "~/.dotfiles/config/vicinae"
"~/.config/zsh" = "~/.dotfiles/config/zsh"
"~/.zshenv" = "~/.dotfiles/config/zshenv/.zshenv"

[bootstrap.hooks]
post-tools = """
TPM_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/tmux/plugins/tpm"

[ ! -d "$TPM_DIR" ] && git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"

"$TPM_DIR/bin/install_plugins"
"""
post-dotfiles = """
mise run bootstrap-personal
"""

